<?php
/**
 * Created by PhpStorm.
 * User: ome
 * Date: 13-06-2018
 * Time: 12:24
 */

namespace backend\models\clientFixed;
use app\models\ClientMultiSelect;
use backend\models\Client;
use common\models\Organisation;
use common\models\User;

/**
 * This is the model class for table "room_listing".
 *
 * @property User $user
 */

class ApplicantFixed extends CommonFixed
{
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client']);
    }
    public function beforeSave($insert)
    {
        $attributes=$this->attributes;
        $client = \backend\modules\mii\jsonData\Applicant::returnData();
        foreach ($attributes as $columnName => $value) {
            foreach ($client as $data) {
                if ($data['type'] == 'select' && !empty($data['multiple'])) {
                    if ($columnName == str_replace("-", "_", $data['name'])) {
                        $valueAttr="multi_select_".$columnName;
                        if(!empty(\Yii::$app->request->post()['Applicant'][$valueAttr])){
                            $this->$columnName=\Yii::$app->request->post()['Applicant'][$valueAttr];
                        }
                    }
                }
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert,$changedAttributes)
    {
        $attributes=$this->attributes;
        $client = \backend\modules\mii\jsonData\Applicant::returnData();
        foreach ($attributes as $columnName => $value) {
            foreach ($client as $data) {
                if ($data['type'] == 'select' && !empty($data['multiple'])) {
                    if ($columnName == str_replace("-", "_", $data['name'])) {
                        $oldData=ClientMultiSelect::find()->where('select_id=:select_id',[':select_id'=>$this->$columnName])->all();
                        if(!empty($oldData)){
                            foreach ($oldData as $data){
                                $data->delete();
                            }
                        }
                        if(!empty(\Yii::$app->request->post()['Applicant'][$columnName])){
                            $valueAttr="multi_select_".$columnName;
                            $array=\Yii::$app->request->post()['Applicant'][$columnName];
                            // create model
                            foreach ($array as $value){
                                $clientMultiSelectModel=  new ClientMultiSelect();
                                $clientMultiSelectModel->select_id=$this->$columnName;
                                $clientMultiSelectModel->name=$value;
                                $clientMultiSelectModel->save(false);
                            }
                        }
                    }
                }
            }
        }
        return parent::afterSave($insert,$changedAttributes); // TODO: Change the autogenerated stub
    }
}