<?php

namespace backend\modules\polling\models;

use backend\modules\mii\jsonData\Applicant;
use Yii;
use yii\helpers\ArrayHelper;

class PollingQuizQuestion extends \backend\modules\polling\models\base\PollingQuizQuestion
{
    const NO_FIELD_EXIST=-1;
    const SHOW_NUMBER=1;
    const MULTIPLE_CHOICE_QUESTION=5;
    const MULTIPLE_RESPONSE=6;
    const UPLOAD_FILE=7;
    const RATING=3;
    const TRUE_FALSE=4;
    const NUMBER=2;
    const DEFAULT_RATING_COUNT=10;
    const DEFAULT_NUMBER_COUNT=10;
   // const POLLING_QUIZ_QUESTION_URL="https://gamificationguru.com/admin/backend/web/polling/show-result/";
    public $show_question_url_result;
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPollingQuizQuestionAnswer()
    {
        return $this->hasOne(PollingQuizQuestionAnswer::className(), ['polling_quiz_question_id' => 'id']);
    }
    public function getAttributeFields()
    {
        $finalArray=[];
        $applicantData=Applicant::returnData();
        foreach ($applicantData as $applicantDatum){
            $finalArray[$applicantDatum['name']]=$applicantDatum['label'];
        }
        return $finalArray;
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public  function applicantEmailValidation($attribute, $params) {
        //find question with email in this poll
        $emailFound=PollingQuizQuestion::find()->where(['polling_quiz_id'=>$this->polling_quiz_id,'applicant_attribute'=>'email'])->count();

       if(!$this->isNewRecord){
           //find current question in table
           $currentRowEmail=PollingQuizQuestion::find()->where(['id'=>$this->id,'applicant_attribute'=>'email'])->count();
           
           if($currentRowEmail==1&&$this->applicant_attribute=='email'){
            //let it save email attribute if table and form has same email attribute
           }
           elseif($currentRowEmail==1&&$this->applicant_attribute!='email'){
            //restrict to save attribute if table has email but form do not
               $this->addError($attribute, 'You cannot change email field');
           }
           elseif (($emailFound>0&&$this->applicant_attribute=='email')) {
                $this->addError($attribute, 'Email field already exist');
            }
            else{

            }
        }
        //if new question
        else{
            if (($emailFound>0 && strtolower($this->applicant_attribute) == 'email')) {
                $this->addError($attribute, 'Email attribute already connected to a question');
            }
            elseif (((!$emailFound>0) && strtolower($this->applicant_attribute) !='email')) {
                $this->addError($attribute, 'Please create a question for  \'email\' Applicant Attribute first');
            }
            else{

            }
        }

    }
}
